const realmNameMap = {
  khadgar: { name: "Khadgar", slug: "khadgar", id: 1080 },
  chromaggus: { name: "Chromaggus", slug: "chromaggus", id: 1083 },
  dentarg: { name: "Dentarg", slug: "dentarg", id: 1084 },
  runetotem: { name: "Runetotem", slug: "runetotem", id: 547 },
  shadowsong: { name: "Shadowsong", slug: "shadowsong", id: 548 },
  silvermoon: { name: "Silvermoon", slug: "silvermoon", id: 549 },
  sunstrider: { name: "Sunstrider", slug: "sunstrider", id: 511 },
  executus: { name: "Executus", slug: "executus", id: 1087 },
  mazrigos: { name: "Mazrigos", slug: "mazrigos", id: 1089 },
  karazhan: { name: "Karazhan", slug: "karazhan", id: 1596 },
  auchindoun: { name: "Auchindoun", slug: "auchindoun", id: 1597 },
  "shattered-halls": {
    name: "Shattered Halls",
    slug: "shattered-halls",
    id: 1598,
  },
  gordunni: { name: "Gordunni", slug: "gordunni", id: 1602 },
  soulflayer: { name: "Soulflayer", slug: "soulflayer", id: 1604 },
  deathguard: { name: "Deathguard", slug: "deathguard", id: 1605 },
  sporeggar: { name: "Sporeggar", slug: "sporeggar", id: 1606 },
  nethersturm: { name: "Nethersturm", slug: "nethersturm", id: 1607 },
  shattrath: { name: "Shattrath", slug: "shattrath", id: 1608 },
  deepholm: { name: "Deepholm", slug: "deepholm", id: 1609 },
  echsenkessel: { name: "Echsenkessel", slug: "echsenkessel", id: 1612 },
  blutkessel: { name: "Blutkessel", slug: "blutkessel", id: 1613 },
  galakrond: { name: "Galakrond", slug: "galakrond", id: 1614 },
  razuvious: { name: "Razuvious", slug: "razuvious", id: 1616 },
  deathweaver: { name: "Deathweaver", slug: "deathweaver", id: 1617 },
  terenas: { name: "Terenas", slug: "terenas", id: 551 },
  thunderhorn: { name: "Thunderhorn", slug: "thunderhorn", id: 552 },
  turalyon: { name: "Turalyon", slug: "turalyon", id: 553 },
  ravencrest: { name: "Ravencrest", slug: "ravencrest", id: 554 },
  "shattered-hand": { name: "Shattered Hand", slug: "shattered-hand", id: 556 },
  spinebreaker: { name: "Spinebreaker", slug: "spinebreaker", id: 558 },
  stormscale: { name: "Stormscale", slug: "stormscale", id: 560 },
  "earthen-ring": { name: "Earthen Ring", slug: "earthen-ring", id: 561 },
  alexstrasza: { name: "Alexstrasza", slug: "alexstrasza", id: 562 },
  alleria: { name: "Alleria", slug: "alleria", id: 563 },
  antonidas: { name: "Antonidas", slug: "antonidas", id: 564 },
  blackhand: { name: "Blackhand", slug: "blackhand", id: 566 },
  gilneas: { name: "Gilneas", slug: "gilneas", id: 567 },
  kargath: { name: "Kargath", slug: "kargath", id: 568 },
  khazgoroth: { name: "Khaz'goroth", slug: "khazgoroth", id: 569 },
  madmortem: { name: "Madmortem", slug: "madmortem", id: 571 },
  zuluhed: { name: "Zuluhed", slug: "zuluhed", id: 573 },
  nozdormu: { name: "Nozdormu", slug: "nozdormu", id: 574 },
  perenolde: { name: "Perenolde", slug: "perenolde", id: 575 },
  aegwynn: { name: "Aegwynn", slug: "aegwynn", id: 577 },
  "dun-morogh": { name: "Dun Morogh", slug: "dun-morogh", id: 600 },
  thrall: { name: "Thrall", slug: "thrall", id: 604 },
  theradras: { name: "Theradras", slug: "theradras", id: 605 },
  genjuros: { name: "Genjuros", slug: "genjuros", id: 606 },
  balnazzar: { name: "Balnazzar", slug: "balnazzar", id: 607 },
  wrathbringer: { name: "Wrathbringer", slug: "wrathbringer", id: 609 },
  talnivarr: { name: "Talnivarr", slug: "talnivarr", id: 1090 },
  emeriss: { name: "Emeriss", slug: "emeriss", id: 1091 },
  drakthul: { name: "Drak'thul", slug: "drakthul", id: 1092 },
  ahnqiraj: { name: "Ahn'Qiraj", slug: "ahnqiraj", id: 1093 },
  ysera: { name: "Ysera", slug: "ysera", id: 1097 },
  malygos: { name: "Malygos", slug: "malygos", id: 1098 },
  anetheron: { name: "Anetheron", slug: "anetheron", id: 1104 },
  nazjatar: { name: "Nazjatar", slug: "nazjatar", id: 1105 },
  tichondrius: { name: "Tichondrius", slug: "tichondrius", id: 1106 },
  "steamwheedle-cartel": {
    name: "Steamwheedle Cartel",
    slug: "steamwheedle-cartel",
    id: 1117,
  },
  "die-ewige-wacht": {
    name: "Die ewige Wacht",
    slug: "die-ewige-wacht",
    id: 1118,
  },
  "die-todeskrallen": {
    name: "Die Todeskrallen",
    slug: "die-todeskrallen",
    id: 1119,
  },
  "die-arguswacht": {
    name: "Die Arguswacht",
    slug: "die-arguswacht",
    id: 1121,
  },
  uldaman: { name: "Uldaman", slug: "uldaman", id: 1122 },
  dragonblight: { name: "Dragonblight", slug: "dragonblight", id: 507 },
  "tarren-mill": { name: "Tarren Mill", slug: "tarren-mill", id: 1306 },
  cthun: { name: "C'Thun", slug: "cthun", id: 1381 },
  alonsus: { name: "Alonsus", slug: "alonsus", id: 1391 },
  "blades-edge": { name: "Blade's Edge", slug: "blades-edge", id: 1416 },
  doomhammer: { name: "Doomhammer", slug: "doomhammer", id: 505 },
  "twilights-hammer": {
    name: "Twilight's Hammer",
    slug: "twilights-hammer",
    id: 513,
  },
  daggerspine: { name: "Daggerspine", slug: "daggerspine", id: 526 },
  sargeras: { name: "Sargeras", slug: "sargeras", id: 546 },
  "emerald-dream": { name: "Emerald Dream", slug: "emerald-dream", id: 508 },
  quelthalas: { name: "Quel'Thalas", slug: "quelthalas", id: 623 },
  bloodscalp: { name: "Bloodscalp", slug: "bloodscalp", id: 522 },
  "burning-blade": { name: "Burning Blade", slug: "burning-blade", id: 523 },
  crushridge: { name: "Crushridge", slug: "crushridge", id: 525 },
  dragonmaw: { name: "Dragonmaw", slug: "dragonmaw", id: 528 },
  dunemaul: { name: "Dunemaul", slug: "dunemaul", id: 529 },
  dethecus: { name: "Dethecus", slug: "dethecus", id: 531 },
  durotan: { name: "Durotan", slug: "durotan", id: 535 },
  aggramar: { name: "Aggramar", slug: "aggramar", id: 500 },
  arathor: { name: "Arathor", slug: "arathor", id: 501 },
  azjolnerub: { name: "Azjol-Nerub", slug: "azjolnerub", id: 503 },
  draenor: { name: "Draenor", slug: "draenor", id: 506 },
  voljin: { name: "Vol'jin", slug: "voljin", id: 510 },
  arakarahm: { name: "Arak-arahm", slug: "arakarahm", id: 512 },
  zenedar: { name: "Zenedar", slug: "zenedar", id: 515 },
  agamaggan: { name: "Agamaggan", slug: "agamaggan", id: 518 },
  bladefist: { name: "Bladefist", slug: "bladefist", id: 521 },
  "argent-dawn": { name: "Argent Dawn", slug: "argent-dawn", id: 536 },
  onyxia: { name: "Onyxia", slug: "onyxia", id: 610 },
  nefarian: { name: "Nefarian", slug: "nefarian", id: 612 },
  "das-syndikat": { name: "Das Syndikat", slug: "das-syndikat", id: 614 },
  "laughing-skull": { name: "Laughing Skull", slug: "laughing-skull", id: 621 },
  neptulon: { name: "Neptulon", slug: "neptulon", id: 624 },
  "twisting-nether": {
    name: "Twisting Nether",
    slug: "twisting-nether",
    id: 625,
  },
  "the-maelstrom": { name: "The Maelstrom", slug: "the-maelstrom", id: 627 },
  bloodfeather: { name: "Bloodfeather", slug: "bloodfeather", id: 630 },
  frostwhisper: { name: "Frostwhisper", slug: "frostwhisper", id: 632 },
  korgall: { name: "Kor'gall", slug: "korgall", id: 633 },
  "defias-brotherhood": {
    name: "Defias Brotherhood",
    slug: "defias-brotherhood",
    id: 635,
  },
  rashgarroth: { name: "Rashgarroth", slug: "rashgarroth", id: 642 },
  "les-sentinelles": {
    name: "Les Sentinelles",
    slug: "les-sentinelles",
    id: 647,
  },
  suramar: { name: "Suramar", slug: "suramar", id: 1331 },
  garrosh: { name: "Garrosh", slug: "garrosh", id: 1401 },
  arygos: { name: "Arygos", slug: "arygos", id: 1406 },
  teldrassil: { name: "Teldrassil", slug: "teldrassil", id: 1407 },
  lordaeron: { name: "Lordaeron", slug: "lordaeron", id: 1409 },
  terokkar: { name: "Terokkar", slug: "terokkar", id: 1415 },
  baelgun: { name: "Baelgun", slug: "baelgun", id: 565 },
  chogall: { name: "Cho'gall", slug: "chogall", id: 545 },
  nordrassil: { name: "Nordrassil", slug: "nordrassil", id: 618 },
  sylvanas: { name: "Sylvanas", slug: "sylvanas", id: 628 },
  drekthar: { name: "Drek'Thar", slug: "drekthar", id: 641 },
  ghostlands: { name: "Ghostlands", slug: "ghostlands", id: 1588 },
  "the-shatar": { name: "The Sha'tar", slug: "the-shatar", id: 1595 },
  naxxramas: { name: "Naxxramas", slug: "naxxramas", id: 1624 },
  arthas: { name: "Arthas", slug: "arthas", id: 578 },
  azshara: { name: "Azshara", slug: "azshara", id: 579 },
  blackmoore: { name: "Blackmoore", slug: "blackmoore", id: 580 },
  destromath: { name: "Destromath", slug: "destromath", id: 582 },
  eredar: { name: "Eredar", slug: "eredar", id: 583 },
  frostwolf: { name: "Frostwolf", slug: "frostwolf", id: 585 },
  kiljaeden: { name: "Kil'jaeden", slug: "kiljaeden", id: 589 },
  malganis: { name: "Mal'Ganis", slug: "malganis", id: 590 },
  "zirkel-des-cenarius": {
    name: "Zirkel des Cenarius",
    slug: "zirkel-des-cenarius",
    id: 592,
  },
  vashj: { name: "Vashj", slug: "vashj", id: 629 },
  hyjal: { name: "Hyjal", slug: "hyjal", id: 542 },
  ulduar: { name: "Ulduar", slug: "ulduar", id: 1323 },
  "howling-fjord": { name: "Howling Fjord", slug: "howling-fjord", id: 1615 },
  alakir: { name: "Al'Akir", slug: "alakir", id: 519 },
  stormreaver: { name: "Stormreaver", slug: "stormreaver", id: 559 },
  magtheridon: { name: "Magtheridon", slug: "magtheridon", id: 622 },
  "lightnings-blade": {
    name: "Lightning's Blade",
    slug: "lightnings-blade",
    id: 637,
  },
  "kirin-tor": { name: "Kirin Tor", slug: "kirin-tor", id: 537 },
  archimonde: { name: "Archimonde", slug: "archimonde", id: 539 },
  elune: { name: "Elune", slug: "elune", id: 540 },
  "chamber-of-aspects": {
    name: "Chamber of Aspects",
    slug: "chamber-of-aspects",
    id: 1307,
  },
  ravenholdt: { name: "Ravenholdt", slug: "ravenholdt", id: 1308 },
  eonar: { name: "Eonar", slug: "eonar", id: 1310 },
  veknilash: { name: "Vek'nilash", slug: "veknilash", id: 1298 },
  frostmane: { name: "Frostmane", slug: "frostmane", id: 1300 },
  bloodhoof: { name: "Bloodhoof", slug: "bloodhoof", id: 504 },
  kaelthas: { name: "Kael'thas", slug: "kaelthas", id: 543 },
  haomarush: { name: "Haomarush", slug: "haomarush", id: 638 },
  "khaz-modan": { name: "Khaz Modan", slug: "khaz-modan", id: 640 },
  varimathras: { name: "Varimathras", slug: "varimathras", id: 645 },
  hakkar: { name: "Hakkar", slug: "hakkar", id: 646 },
  blackrock: { name: "Blackrock", slug: "blackrock", id: 581 },
  kelthuzad: { name: "Kel'Thuzad", slug: "kelthuzad", id: 588 },
  mannoroth: { name: "Mannoroth", slug: "mannoroth", id: 591 },
  proudmoore: { name: "Proudmoore", slug: "proudmoore", id: 593 },
  garona: { name: "Garona", slug: "garona", id: 509 },
  "darkmoon-faire": {
    name: "Darkmoon Faire",
    slug: "darkmoon-faire",
    id: 1317,
  },
  veklor: { name: "Vek'lor", slug: "veklor", id: 1318 },
  mugthol: { name: "Mug'thol", slug: "mugthol", id: 1319 },
  taerar: { name: "Taerar", slug: "taerar", id: 1320 },
  dalvengyr: { name: "Dalvengyr", slug: "dalvengyr", id: 1321 },
  rajaxx: { name: "Rajaxx", slug: "rajaxx", id: 1322 },
  malorne: { name: "Malorne", slug: "malorne", id: 1324 },
  "der-abyssische-rat": {
    name: "Der abyssische Rat",
    slug: "der-abyssische-rat",
    id: 1326,
  },
  "der-mithrilorden": {
    name: "Der Mithrilorden",
    slug: "der-mithrilorden",
    id: 1327,
  },
  ambossar: { name: "Ambossar", slug: "ambossar", id: 1330 },
  krasus: { name: "Krasus", slug: "krasus", id: 1332 },
  arathi: { name: "Arathi", slug: "arathi", id: 1334 },
  ysondre: { name: "Ysondre", slug: "ysondre", id: 1335 },
  eldrethalas: { name: "Eldre'Thalas", slug: "eldrethalas", id: 1336 },
  kilrogg: { name: "Kilrogg", slug: "kilrogg", id: 1311 },
  wildhammer: { name: "Wildhammer", slug: "wildhammer", id: 1313 },
  saurfang: { name: "Saurfang", slug: "saurfang", id: 1314 },
  nemesis: { name: "Nemesis", slug: "nemesis", id: 1316 },
  fordragon: { name: "Fordragon", slug: "fordragon", id: 1623 },
  "borean-tundra": { name: "Borean Tundra", slug: "borean-tundra", id: 1625 },
  "les-clairvoyants": {
    name: "Les Clairvoyants",
    slug: "les-clairvoyants",
    id: 1626,
  },
  skullcrusher: { name: "Skullcrusher", slug: "skullcrusher", id: 557 },
  lothar: { name: "Lothar", slug: "lothar", id: 570 },
  sinstralis: { name: "Sinstralis", slug: "sinstralis", id: 533 },
  terrordar: { name: "Terrordar", slug: "terrordar", id: 615 },
  "scarshield-legion": {
    name: "Scarshield Legion",
    slug: "scarshield-legion",
    id: 1096,
  },
  "kul-tiras": { name: "Kul Tiras", slug: "kul-tiras", id: 1082 },
  stormrage: { name: "Stormrage", slug: "stormrage", id: 550 },
  nerzhul: { name: "Ner'zhul", slug: "nerzhul", id: 544 },
  "dun-modr": { name: "Dun Modr", slug: "dun-modr", id: 1378 },
  zuljin: { name: "Zul'jin", slug: "zuljin", id: 1379 },
  uldum: { name: "Uldum", slug: "uldum", id: 1380 },
  sanguino: { name: "Sanguino", slug: "sanguino", id: 1382 },
  shendralar: { name: "Shen'dralar", slug: "shendralar", id: 1383 },
  tyrande: { name: "Tyrande", slug: "tyrande", id: 1384 },
  exodar: { name: "Exodar", slug: "exodar", id: 1385 },
  "los-errantes": { name: "Los Errantes", slug: "los-errantes", id: 1387 },
  lightbringer: { name: "Lightbringer", slug: "lightbringer", id: 1388 },
  darkspear: { name: "Darkspear", slug: "darkspear", id: 1389 },
  "burning-steppes": {
    name: "Burning Steppes",
    slug: "burning-steppes",
    id: 1392,
  },
  "bronze-dragonflight": {
    name: "Bronze Dragonflight",
    slug: "bronze-dragonflight",
    id: 1393,
  },
  anachronos: { name: "Anachronos", slug: "anachronos", id: 1394 },
  "colinas-pardas": {
    name: "Colinas Pardas",
    slug: "colinas-pardas",
    id: 1395,
  },
  ungoro: { name: "Un'Goro", slug: "ungoro", id: 1400 },
  illidan: { name: "Illidan", slug: "illidan", id: 541 },
  rexxar: { name: "Rexxar", slug: "rexxar", id: 1099 },
  guldan: { name: "Gul'dan", slug: "guldan", id: 587 },
  aszune: { name: "Aszune", slug: "aszune", id: 502 },
  "aerie-peak": { name: "Aerie Peak", slug: "aerie-peak", id: 1312 },
  xavius: { name: "Xavius", slug: "xavius", id: 639 },
  throkferoth: { name: "Throk'Feroth", slug: "throkferoth", id: 643 },
  minahonda: { name: "Minahonda", slug: "minahonda", id: 1386 },
  tirion: { name: "Tirion", slug: "tirion", id: 1328 },
  senjin: { name: "Sen'jin", slug: "senjin", id: 602 },
  trollbane: { name: "Trollbane", slug: "trollbane", id: 1088 },
  amanthul: { name: "Aman'Thul", slug: "amanthul", id: 601 },
  bronzebeard: { name: "Bronzebeard", slug: "bronzebeard", id: 1081 },
  "die-aldor": { name: "Die Aldor", slug: "die-aldor", id: 1618 },
  "temple-noir": { name: "Temple noir", slug: "temple-noir", id: 1622 },
  eversong: { name: "Eversong", slug: "eversong", id: 1925 },
  thermaplugg: { name: "Thermaplugg", slug: "thermaplugg", id: 1926 },
  grom: { name: "Grom", slug: "grom", id: 1927 },
  goldrinn: { name: "Goldrinn", slug: "goldrinn", id: 1928 },
  blackscar: { name: "Blackscar", slug: "blackscar", id: 1929 },
  forscherliga: { name: "Forscherliga", slug: "forscherliga", id: 516 },
  eitrigg: { name: "Eitrigg", slug: "eitrigg", id: 1123 },
  todeswache: { name: "Todeswache", slug: "todeswache", id: 1405 },
  dalaran: { name: "Dalaran", slug: "dalaran", id: 538 },
  frostmourne: { name: "Frostmourne", slug: "frostmourne", id: 584 },
  malfurion: { name: "Malfurion", slug: "malfurion", id: 572 },
  kragjin: { name: "Krag'jin", slug: "kragjin", id: 616 },
  gorgonnash: { name: "Gorgonnash", slug: "gorgonnash", id: 586 },
  "burning-legion": { name: "Burning Legion", slug: "burning-legion", id: 524 },
  azuremyst: { name: "Azuremyst", slug: "azuremyst", id: 1417 },
  anubarak: { name: "Anub'arak", slug: "anubarak", id: 608 },
  nerathor: { name: "Nera'thor", slug: "nerathor", id: 611 },
  "kult-der-verdammten": {
    name: "Kult der Verdammten",
    slug: "kult-der-verdammten",
    id: 613,
  },
  "der-rat-von-dalaran": {
    name: "Der Rat von Dalaran",
    slug: "der-rat-von-dalaran",
    id: 617,
  },
  hellscream: { name: "Hellscream", slug: "hellscream", id: 619 },
  ragnaros: { name: "Ragnaros", slug: "ragnaros", id: 626 },
  darksorrow: { name: "Darksorrow", slug: "darksorrow", id: 631 },
  "the-venture-co": { name: "The Venture Co", slug: "the-venture-co", id: 636 },
  "grim-batol": { name: "Grim Batol", slug: "grim-batol", id: 1303 },
  jaedenar: { name: "Jaedenar", slug: "jaedenar", id: 1304 },
  kazzak: { name: "Kazzak", slug: "kazzak", id: 1305 },
  moonglade: { name: "Moonglade", slug: "moonglade", id: 1085 },
  "conseil-des-ombres": {
    name: "Conseil des Ombres",
    slug: "conseil-des-ombres",
    id: 644,
  },
  nathrezim: { name: "Nathrezim", slug: "nathrezim", id: 594 },
  "das-konsortium": {
    name: "Das Konsortium",
    slug: "das-konsortium",
    id: 1619,
  },
  boulderfist: { name: "Boulderfist", slug: "boulderfist", id: 1299 },
  deathwing: { name: "Deathwing", slug: "deathwing", id: 527 },
  "area-52": { name: "Area 52", slug: "area-52", id: 1404 },
  "die-nachtwache": {
    name: "Die Nachtwache",
    slug: "die-nachtwache",
    id: 1333,
  },
  "booty-bay": { name: "Booty Bay", slug: "booty-bay", id: 1924 },
  "lich-king": { name: "Lich King", slug: "lich-king", id: 1603 },
  hellfire: { name: "Hellfire", slug: "hellfire", id: 1587 },
  outland: { name: "Outland", slug: "outland", id: 1301 },
  greymane: { name: "Greymane", slug: "greymane", id: 1610 },
  medivh: { name: "Medivh", slug: "medivh", id: 517 },
  "die-silberne-hand": {
    name: "Die Silberne Hand",
    slug: "die-silberne-hand",
    id: 576,
  },
  nagrand: { name: "Nagrand", slug: "nagrand", id: 1589 },
  azuregos: { name: "Azuregos", slug: "azuregos", id: 1922 },
  ashenvale: { name: "Ashenvale", slug: "ashenvale", id: 1923 },
  norgannon: { name: "Norgannon", slug: "norgannon", id: 1408 },
};

export default function (realmName: string) {
  return realmNameMap[realmName].name;
}
